version: '3.7'
services:
  service1:
    image: 127.0.0.1:4999/service1
    build: ./service1
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
  service2:
    image: 127.0.0.1:4999/service2
    build: ./service2
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
